routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::get('/empleados','EmpleadoController@index');
//Route::get('/empleados/create', 'EmpleadoController@create');

Route::get('/inicio', function () {
    return view('/layouts/home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//CREA LA DE TODOS LOS METODOS AUTOMATICAMENTE
Route::resource('empleados', 'EmpleadoController');

app/Empleado.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Empleado extends Model
{
    protected $table = 'empleados';
    public $timestamps = false;
    protected $fillable = ['Nombre', 'ApellidoP', 'ApellidoM','Telefono','Correo','Puesto','Turno','Foto'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmpleadoController.php
<?php

namespace App\Http\Controllers;

use App\Empleado;
use Illuminate\Http\Request;

class EmpleadoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $empleados = Empleado::all();
        return view('empleados.index', compact('empleados'));

        /*
        $datos['empleados'] = Empleado::paginate(5);
        return view('empleados.index',$datos);*/
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('empleados.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        Empleado::create($request->all());
        return redirect()->route('empleados.index');

        /*$datosEmpleado = request()->all();
        $datosEmpleado = request()->except('_token');

        //INSERTAR EN LA BASE DE DATOS
        Empleado::insert($datosEmpleado);
        
        //return response()->json($datosEmpleado);
        return redirect()->route('empleados.index');*/
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Empleado  $empleado
     * @return \Illuminate\Http\Response
     */
    public function show(Empleado $empleado)
    {
        return view('empleados.show', compact('empleado'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Empleado  $empleado
     * @return \Illuminate\Http\Response
     */
    public function edit(Empleado $empleado)
    {

        return view('empleados.form', compact('empleado'));

        /*
        //DEVULVE TODA LA INFO QUE CORRESPONDE A ESE ID
        $empleado = Empleado::findOrFail($id);
        //ENVIA LA INFORMACION DEL $empleado
        return view('empleados.edit',compact('empleado'));*/
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Empleado  $empleado
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Empleado $empleado)
    {

        $empleado->Nombre = $request->Nombre;
        $empleado->ApellidoP = $request->ApellidoP;
        $empleado->ApellidoM = $request->ApellidoM;
        $empleado->Correo = $request->Correo;
        $empleado->Telefono = $request->Telefono;
        $empleado->Puesto = $request->Puesto;
        $empleado->Turno = $request->Turno;
        $empleado->Foto = $request->Foto;

        $empleado->save();
        return redirect()->route('empleados.show', $empleado->id);

        /*
        $datosEmpleado = request()->except(['_token','_method']);
        EmpleadoDB::where('id','=',$id)->update($datosEmpleado);

        //DEVULVE TODA LA INFO QUE CORRESPONDE A ESE ID
        $empleado = Empleado::findOrFail($id);
        //ENVIA LA INFORMACION DEL $empleado
        return view('empleados.edit',compact('empleado'));*/

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Empleado  $empleado
     * @return \Illuminate\Http\Response
     */
    public function destroy(Empleado $empleado)
    {
        $empleado->delete();
        return redirect()->route('empleados.index');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/empleados/form.blade.php
@extends('layouts.base')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if(isset($empleado))
                      <form action="{{ route('empleados.update', $empleado->id) }}" method="POST">
                      <input type="hidden" name="_method" value="PATCH">
                    @else
                      <form action="{{ route('empleados.store') }}" method="POST">
                    @endif
                    
                      @csrf
                      <div class="form-group">
                          <label for="Nombre">Nombre</label>
                          <input type="text" name="Nombre" value="{{ $empleado->Nombre ?? '' }}" class="form-control" id="Nombre">
                      </div>
                      <div class="form-group">
                          <label for="ApellidoP">Apellido Paterno</label>
                          <input type="text" name="ApellidoP" value="{{ $empleado->ApellidoP ?? '' }}" class="form-control" id="ApellidoP">
                      </div>
                      <div class="form-group">
                          <label for="ApellidoM">Apellido Materno</label>
                          <input type="text" name="ApellidoM" value="{{ $empleado->ApellidoM ?? '' }}" class="form-control" id="ApellidoM">
                      </div>
                      <div class="form-group">
                          <label for="Telefono">Telefono</label>
                          <input type="text" name="Telefono" value="{{ $empleado->Telefono ?? '' }}" class="form-control" id="Telefono">
                      </div>
                      <div class="form-group">
                          <label for="Correo">Correo</label>
                          <input type="email" name="Correo" value="{{ $empleado->Correo ?? '' }}" class="form-control" id="Correo">
                      </div>
                      <div class="form-group">
                          <label for="Puesto">Puesto</label>
                          <input type="text" name="Puesto" value="{{ $empleado->Puesto ?? '' }}" class="form-control" id="Puesto">
                      </div>
                      <div class="form-group">
                          <label for="Turno">Turno</label>
                          <input type="text" name="Turno" value="{{ $empleado->Turno ?? '' }}" class="form-control" id="Turno">
                      </div>
                      <div class="form-group">
                          <label for="Foto">Foto</label>
                          <input type="text" name="Foto" value="{{ $empleado->Foto ?? '' }}" class="form-control" id="Foto">
                      </div>

                      <button type="submit" class="btn btn-primary">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/empleados/index.blade.php
@extends('layouts.base')
@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
        <div class="card">
            <div class="card-header">Empleados</div>
            <div class="card-body">

                <a href="{{ route('empleados.create') }}" class="btn btn-success btn-sm">Agregar Empleado</a>
                <br/> <br/>
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th>#</th>
                            <!--<th>Foto</th>-->
                            <th>Nombre Completo</th>
                            <th>Telefono</th>
                            <th>Correo</th>
                            <th>Puesto</th>
                            <th>Turno</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    
                    <tbody>
                        @foreach($empleados as $empleado)
                        <tr>
                            <!--<td>{{$empleado->Foto}}</td>-->
                            <td>{{$empleado->id}}</td>
                            <td>{{$empleado->Nombre.' '.$empleado->ApellidoP.' '.$empleado->ApellidoM }}</td>
                            <td>{{$empleado->Telefono}}</td>
                            <td>{{$empleado->Correo}}</td>
                            <td>{{$empleado->Puesto}}</td>
                            <td>{{$empleado->Turno}}</td>
                            <td>
                                <a href="{{ route('empleados.show', $empleado->id) }}" class="btn btn-sm btn-info">Ver Detalle</a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>

                </table>
            </div>
        </div>
        </div>
    </div>
</div>





<!--
<div class="container">
    <table class="table table-light">


        <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>Foto</th>
                <th>Nombre Completo</th>
                <th>Telefono</th>
                <th>Correo</th>
                <th>Puesto</th>
                <th>Turno</th>
                <th>Acciones</th>
            </tr>
        </thead>


        <tbody>
         $empleados -> FUE DECLARAD EN EMPLEADOCONTROLLER 
        @foreach($empleados as $empleado)
            <tr>
                <td>{{$loop->iteration}}</td>
                <td>{{$empleado->Foto}}</td>
                <td>{{$empleado->Nombre.' '.$empleado->ApellidoP.' '.$empleado->ApellidoM }}</td>
                <td>{{$empleado->Telefono}}</td>
                <td>{{$empleado->Correo}}</td>
                <td>{{$empleado->Puesto}}</td>
                <td>{{$empleado->Turno}}</td>
                <td>
                
                <a href="{{ url('/empleados/'.$empleado->id.'/edit') }}">
                    Editar
                </a>
                
                | 

                <form method="post" action="{{url('/empleados/'.$empleado->id)}}">

                TOKEN
                {{csrf_field()}}
                {{ method_field('DELETE')}}
                <button type="submit" onclick="return confirm('¿Desea borrar el registo?');">Borrar</button>
                    
                </form>


                </td>
            </tr>

        @endforeach
        </tbody>
    </table>

</div>-->

@endsection

resources/views/empleados/show.blade.php
@extends('layouts.base')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">Información del Empleado</div>

                <div class="card-body">
                  <a href="{{ route('empleados.index') }}" class="btn btn-default btn-sm">Listado de Empleados</a>
                    <table class="table">
                      <thead class="thead-dark">
                        <tr>
                            <th>ID</th>
                            <th>Nombre Completo</th>
                            <th>Telefono</th>
                            <th>Correo</th>
                            <th>Puesto</th>
                            <th>Turno</th>
                            <th>Acciones</th>
                      </thead>
                      <tbody>
                          <tr>
                            <td>{{$empleado->id}}</td>
                            <td>{{$empleado->Nombre}}</td>
                            <td>{{$empleado->Telefono}}</td>
                            <td>{{$empleado->Correo}}</td>
                            <td>{{$empleado->Puesto}}</td>
                            <td>{{$empleado->Turno}}</td>
                            <td>
                              <a href="{{ route('empleados.edit', $empleado->id) }}" class="btn btn-sm btn-warning">Editar</a>
                              <form action="" method="POST">
                                @method('DELETE')
                                @csrf
                                <button type="submit" class="btn btn-sm btn-danger">Eliminar</button>
                              </form>
                            </td>
                          </tr>
                      </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ 'Inicio' }}
                </a>
                <a class="navbar-brand" href="{{ url('/empleados') }}">
                    {{ 'Empleados'}}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/home.blade.php
@extends('layouts.base')
@section('content')

hola

@endsection